### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by tinof** [philip/MySQLConverterTool#12]
After clicking "start the conversion" I get the following error:

```
403 Forbidden

A potentially unsafe operation has been detected in your request to this site.
```

I realise it probably has something do with my EasyEngine stacks security options, but I have live sites on this server so I would preferably not go with trial and error method.

Any help is greatly appreciated.

Using Ubuntu 14.04, Nginx 1.9 and php 5.6 (EasyEngine stack settings)

**Comment by philip** [comment]
@tinof Could you describe exactly what you did, such as converting a file or dir or snippet, and enable update files and/or backup files? Also, does the nginx log contain anything related to the operation?

**Comment by philip** [comment]
@tinof I guess, if I were you, I'd copy the code to a different location (e.g., your laptop) then execute there. Using PHP's built-in web-server makes things easy, so consider using that. The related documentation here was updated accordingly.

In the meantime, I'm closing this issue as I don't think it's a code problem, per se.
