### ISSUE TITLE
converter ignores functions with names in upper case

### ISSUE THREAD

**Issue by semoriil** [philip/MySQLConverterTool#15]
Such functions left untouched:
* MYSQL_QUERY
* MYSQL_ESCAPE_STRING
* MYSQL_FETCH_OBJECT
while in lower case all was changed.

**Comment by semoriil** [comment]
workaround: preprocess files with something like 
`sed -i -re s/\\\<\(mysql_\\w+\)\\\>/\\L\\1/gi your.php`

**Comment by semoriil** [comment]
Converter checks for function name in such way:
`if (isset($this->mysql_funcs[$text]))`
And `$this->mysql_funcs` is array with supported function names in lowercase.

**Comment by philip** [comment]
Interesting issue, agreed that it needs to be fixed. Adding this to the #1 todo.

**Comment by semoriil** [comment]
I forked this repo and got this fixed in mine. But not really tested.
Same for mysql_set_charset - just added required classes (not me).
[my fork](https://github.com/semoriil/MySQLConverterTool)

Not sure what to do with this...

**Comment by philip** [comment]
This was fixed via pull request #17 -- thank you for the bug report!
