### ISSUE TITLE
Not using mysqli_select_db?

### ISSUE THREAD

**Issue by gavindphillips** [philip/MySQLConverterTool#20]
Hi there,

Firstly thanks for this, it's saving me a lot of time!

Is there a reason why mysql_select_db is being converted to a mysqli_query USE statement rather than just using mysqli_select_db?

Not sure if I'm missing something here but looks like it could run though ParReversed too?

Thanks

**Comment by philip** [comment]
Good question, adding "research bug #20" to my immediate todo.

**Comment by philip** [comment]
@johannes can you think of reasons why mysqli_select_db() is not being used?

**Comment by johannes** [comment]
My guess is that this simply predates the mysqli_select_db() function. I
see no real reason why mysqli_select_db() shouldn't be used. :-)

**Comment by philip** [comment]
This is now fixed, thanks for the bug report :)
