### ISSUE TITLE
mysql_list_tables quote issues

### ISSUE THREAD

**Issue by e-dschungel** [philip/MySQLConverterTool#22]
I think mysql_list_tables should be converted to SHOW_TABLES FROM \`$db\` (regard the backticks). Otherwise db names which need quotation like test-01 are not handled correctly.

**Comment by philip** [comment]
Thanks for the report, this is now fixed. Sorry for taking so long to merge the change :) 

@e-dschungel Please confirm that it fixes the issue for you.

**Comment by e-dschungel** [comment]
@philip Yes, this fixes the issue for me.

**Comment by philip** [comment]
Excellent!
