### ISSUE TITLE
Error when trying GUI method

### ISSUE THREAD

**Issue by dignidave** [philip/MySQLConverterTool#25]
Sorry if this is a really dumb problem but I'm very new to php and SQL im using both for a school project and so far its been awful.

I took the code you had for the GUI method and made a notepad++ file and put it in my htdocs folder of xampp but when I go to execute it using the apache local server it gives me this error:

Parse error: syntax error, unexpected 'wget' (T_STRING), expecting variable (T_VARIABLE) or '$' in C:\xampp\htdocs\converter\help.php on line 2

What am I doing wrong?

`<?php
$ wget https://github.com/philip/MySQLConverterTool/archive/master.zip;
$ unzip master.zip;
$ cd MySQLConverterTool-master/GUI;
$ php -S localhost:8000;
?>`

That is my code

**Comment by cudencuden** [comment]
try cloning https://github.com/philip/MySQLConverterTool.wiki.git or you can download this https://github.com/philip/MySQLConverterTool/archive/master.zip... then place the extracted folder into htdocs... then browse to it.. ex localhost or localhost/MySQLConverterTool

**Comment by philip** [comment]
@dignidave I think you should start by following a few basic PHP tutorials. Diving into an old complicated script like MySQLConverterTool is not recommended, and is not really something to learn from.

But what you quoted is not meant to be a PHP script. Those are commands meant to be executed from the command line. For example, `wget` is a tool that can be used to download stuff. You could just use the link instead, in our browser. `php -S` is a command to invoke PHP's internal web server from the command line, which is simple and doesn't require a more complicated setup like xampp. But, that's only an option, you can use Apache instead.

This topic goes beyond the scope of MySQLConverterTool, though, so I'm closing this bug. Good luck :)
