### ISSUE TITLE
Parse Error

### ISSUE THREAD

**Issue by Rhyfelwr** [philip/MySQLConverterTool#26]
Convert a file

Parse error: syntax error, unexpected T_FUNCTION, expecting ')' in /opt/lampp/htdocs/MySQLConverterTool-master/Converter.php on line 364

**Comment by philip** [comment]
Interesting and surprising, thanks for the report, I'll take a look on Monday.

**Comment by philip** [comment]
The code that generates that parse error uses anonymous functions that were added in PHP 5.3. The code was added in change a58fc775df0654ea0e6060150b2ca1eda9d91e86 about a year ago.

It'd make sense for MySQLConverterTool to work in older PHP versions as this converts old MySQL code, so I'll look into this later this week and hopefully make all the code work with old PHP versions again.

Thanks for the report.

**Comment by Rhyfelwr** [comment]
Hi Philip

I ran this on php Ver 5.2.0 which would explain it!

It’s on an old internal LAMP machine, hence the upgrade in code before we upgrade the platform.

Glad it helped!

**Comment by philip** [comment]
@Rhyfelwr Please give it another try with the latest change (change #dc496d1) and hopefully this fixes the issue. I don't have PHP 5.2 or lower to test right now, but will do so eventually.
