### ISSUE TITLE
CLI example

### ISSUE THREAD

**Issue by marcovtwout** [philip/MySQLConverterTool#6]
Maybe it's handy to add a cli example showing how to pass arguments (because -- is required):

```
php -f cli.php -- -d /path/to/project
```

**Comment by philip** [comment]
The README was updated to simply use the likes of:
````
php cli.php -d /path
````
PHP's -f parameter is optional, and has since been removed from the CLI example. This simplifies things.

Thanks for reporting this issue.

**Comment by bannostookaylo** [comment]
I'm running this but none of the files are changing 
```
php cli.php -d /path -p "*.php"
```
as it runs I can see the contents of the files fly past my screen... but nothing ever saves

**Comment by bannostookaylo** [comment]
if i do this it works
```
php cli.php -f filename > tmp/filename
```
but thats gonna be an issue 1 because of how many files and 2 because of how many directories... i'd like to use recursive feature of the -d flag.

**Comment by bannostookaylo** [comment]
Not sure if commenting on closed tickets is proper edicate so I create a new ticket here https://github.com/philip/MySQLConverterTool/issues/30
