### ISSUE TITLE
Exclude hidden files/directories

### ISSUE THREAD

**Issue by marcovtwout** [philip/MySQLConverterTool#7]
Content in hidden files or directories is also converted. Is there any way to prevent this?

**Comment by philip** [comment]
What do you mean by "hidden"?

**Comment by marcovtwout** [comment]
Files or directories starting with a dot.

**Comment by philip** [comment]
@marcovtwout Probably too late for you now (sorry!), but this is now fixed. There is a new option to enter a . to skip files/dirs that begin with a dot, or to pass in a regular expression to preg_match. Thanks for the bug report :)

**Comment by marcovtwout** [comment]
Better late than never :) Thank you.
